### ISSUE TITLE
Switching between a header and a source file can swap to object files

### ISSUE THREAD

**Issue by pajlada** [ericcurtin/CurtineIncSw.vim#11]
When using the plugin to switch between a header and a source file, it can detect files that aren't source or header-files.

Example folder structure:
`src/test.cpp`
`src/test.hpp`
`obj/test.cpp.o`

When switching from test.hpp it would find both `src/test.cpp` and `src/test.cpp.o`

My suggestion would be to switch out the find cmd to use `-regex` instead of `-iname`, that way we can do something like `-regex ".*test\.c[a-z]*"`. This regex small solves the issue for me, however there are more possible file extensions (i.e. `.c++`) that I haven't fully explored yet.

Before I look more into handling any quirky file extensions and submit a PR I would like to know if using `-regex` is something you would like to support at all.

Thanks!

**Comment by ericcurtin** [comment]
Yeah sure go for it :+1: 

I do worry that this can break support for some platforms. There are lots of find implementations that don't have this option. I say we cross that bridge when we get to it!

**Comment by pajlada** [comment]
The changes in #13 and #14 seems to have fixed my issues, close to the solution I was looking at.
