### ISSUE TITLE
Save and restore cursor position

### ISSUE THREAD

**Issue by kgraefe** [ericcurtin/CurtineIncSw.vim#16]
When switching from the source file to the header file and back to the source file the cursor is moved to the top of the file.

Is that the desired behavior? Because for me this drives the plugin almost useless. Most of the time I just want to quickly look something up or do the same changes in both files (e.g. change a function declaration).

**Comment by ericcurtin** [comment]
We use `e#` command in vim to go back to the previous file, good observation though. Maybe we can ask the question to the vim community to see if there is a similar command that preserves cursor position.

**Comment by ericcurtin** [comment]
I think I'm answering my own question here:

b#

**Comment by ericcurtin** [comment]
Fixed

**Comment by kgraefe** [comment]
Thank you.

Unfortunately it only works after the first switch: https://asciinema.org/a/0cHOjRLgjrLGe7zMlUZsl6vfS

I open the C file, go to the H file and go back to the C file and the cursor is back at the top.

**Comment by ericcurtin** [comment]
Thanks for showing me asciinema, a useful tool. Want to be our latest and greatest contributor and try and fix this @kgraefe ? There's some suggested solutions here https://github.com/vim/vim/issues/8673, such as:

> If that's not enough, you might need to save and restore the cursor position, possibly via `getcurpos()` and `setpos()`, or `winsaveview()` and `winrestview()`. Have also a look at `:help restore-cursor` (although, not quite what you want, but you might still borrow some code/idea from it).

that might work.

**Comment by kgraefe** [comment]
You may assign the issue to me. I cannot say if and when I am able to dive into this, though.

**Comment by kgraefe** [comment]
It works perfectly fine with Vim 8.2.486 on Cygwin. It does not work for me with Vim 8.0.1453 on Ubuntu 18.04.5 and Vim 8.1.2269 on Ubuntu 20.04.2.

I also noticed that on Ubuntu the cursor position is not restored when closing and re-opeing a file. So that is probably the cause and unrelated to this plugin.

**Comment by ericcurtin** [comment]
Fixed in last commit, took the following:

```
" Uncomment the following to have Vim jump to the last position when
" reopening a file
"au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
```

from /etc/vim/vimrc

**Comment by ericcurtin** [comment]
Your last comment gave me a clue that it might be something in the default vimrc file sometimes
