### ISSUE TITLE
Support for inconsistent extensions

### ISSUE THREAD

**Issue by nikulabs** [ericcurtin/CurtineIncSw.vim#4]
It would be nice if there was support for switching between different extensions. In my code base we have ".cpp" implementation files and ".h" headers. Many code bases use a similar scheme.

h <--> c
h <--> cpp
h <--> cxx

**Comment by ericcurtin** [comment]
Will look into this sometime when I get back from vacation

**Comment by ericcurtin** [comment]
91a58340d2c4fcbb7b118697b3f719eecfe10ff5 fixes this

**Comment by nikulabs** [comment]
Works great, thanks!

**Comment by ericcurtin** [comment]
Hope it worked great for ya... This is so long ago I can't even remember making the change 😊
