### ISSUE TITLE
Fails to switch when file opened from parent directory

### ISSUE THREAD

**Issue by JamesWP** [ericcurtin/CurtineIncSw.vim#5]
if I load a file with `$ vim ~/directory/file.cpp` the `~/directory/file.hpp` is not found

**Comment by ericcurtin** [comment]
Does it work when you do this?

cd ~
vim ~/directory/file.cpp

**Comment by ericcurtin** [comment]
A contribution would be welcome to check if the other file in the same directory as the one opened 👍

**Comment by ericcurtin** [comment]
90926ce1aaa6556fbf113b246616a9492ca1df12 fixes this
