### ISSUE TITLE
Search pattern should be in quotes

### ISSUE THREAD

**Issue by christiansteck** [ericcurtin/CurtineIncSw.vim#7]
The search pattern `t:IncSw` should be in quotes to protect it from expansion by the shell. E.g. for me the command `find . -iname foo.h*` fails with `zsh: no matches found: foo.h*`. 

This is also stated in the find manpage:
> ... Please note that you should quote patterns as a matter of course, otherwise the shell will expand any wildcard characters in them.

I think the current `cmd` can be replaced by
`"find . " . dirname . " -type f -iname '" . t:incSw . "' -printf %P -quit`
This also saves the two pipes as `-printf %P` prints the path without trailing newline and `quit` stops after the first result is found.

**Comment by ericcurtin** [comment]
If you open the PR to solve the expansion problem, I'd happily merge!

But not so sure about saving pipes via:

-printf %P -quit

I don't think all find implementations support these args

**Comment by ericcurtin** [comment]
@pajlada kindly fixed this with #10
